name: Linting

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js for the frontend
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies for the frontend
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      # Run ESLint for the frontend
      - name: Run Frontend Lint
        working-directory: ./frontend
        run: npm run lint

      # Setup Node.js for the backend
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies for the backend
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      # Run ESLint for the backend
      - name: Run Backend Lint
        working-directory: ./backend
        run: npm run lint
